5 feature tests
e1cb4ac37s/qna pull request #3
Opened 2021-02-20 07:04 UTC by e1cb4ac37s

2021-02-20 19:00 UTC, vkurennov requested changes

2021-02-21 07:19 UTC, e1cb4ac37s commented on spec/features/answers/delete.spec.rb
> +    scenario 'can not delete answer' do
он есть выше на 20 строке (на момент до начала правок)

2021-02-21 07:22 UTC, e1cb4ac37s commented on app/controllers/answers_controller.rb
>        render :edit
ну да, красная строка это то что я удалил, а зеленая - то что стало, а стало `redirect_to @question, ...`

2021-02-23 11:19 UTC, vkurennov approved these changes

2021-02-23 11:19 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to @question, notice: 'Answer is invalid, try again'
а вот так тоже нельзя, потому что  теряется то, что ввел пользователь и ошибки валидации. ты сейчас это обошел, но это плохое решение, потому что валидации должны выполняться моделью и их может быть гораздо больше одной.
все что нужно - это рендерить (не редиректить) questions/show, ну и в самом этом шаблоне сделать вывод ошибок валидации для ответа

2021-02-23 11:19 UTC, vkurennov commented on app/models/user.rb
> +    return entity.user.id == id if entity&.user
такое сравнение по id соверешнно бессмысленно, т.к. по-прежнему загружается в память весь объект из базы. да и условие тоже грузит эту ассоциаию. а смысл сравнения по _id в том, чтобы этого не делать.

весь метод умещается в одну строку (без return и условий):

`entity.user_id == id`

если у объекта нет поля user_id будет исключение, но это логично, потому что метод предполагает наличие такого поля и если его нет, это исключительная ситуация

2021-02-23 11:19 UTC, vkurennov commented on app/views/questions/show.html.slim
> += render 'shared/errors', resource: question
а зачем здесь еще раз выводить ошибки валидации для вопроса? это же страница уже созданного вопроса, значит, он уже валиден

2021-02-23 11:19 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  - if question.answers.length > 1
1) лучше использовать провекру на `empty?`
2) такая проверка имеет смысл, если есть ветка else, если ее нет, то each и так ничего не сделает, так зачем делать лишние действия?

2021-02-23 11:19 UTC, vkurennov commented on spec/features/answers/delete.spec.rb
> +      expect(page).not_to have_css '.answer__delete'
проверять через css не очень хорошо,  лучше через элементы интерфейса, с которым пользователь может )(или не может) взаимодействовать

2021-02-23 11:19 UTC, vkurennov commented on spec/models/user_spec.rb
> +  describe 'owns? method' do
обычно принято для инстанс-методов писать `describe '#somme_method'`

2021-02-23 11:19 UTC, vkurennov commented on spec/models/user_spec.rb
> +    it 'should return true if entity is created by tested user' do
ставь пустые строки между, тестами и другими блоками кода, это облегчает чтение.

2021-02-23 11:19 UTC, vkurennov commented on spec/models/user_spec.rb
> +      question = subject.questions.create(attributes_for(:question))
это лучше через let задавать

2021-02-23 11:19 UTC, vkurennov commented on spec/models/user_spec.rb
> +      expect(subject.owns?(question)).to be true
можно еще вот так:

`expect(subject).to be_owns(questions)`

т.е. вызов метода перенести вправо от to, добавить be_ и убрать знак вопроса.

правда, лучше будет, если метод назвать вроде `author_of?`

2021-02-23 11:19 UTC, vkurennov commented on spec/models/user_spec.rb
> +      expect(another_user.owns?(question)).to be true
это ты уже протестировал выше. нужно только кейс с false протестировать

2021-02-23 14:05 UTC, merged